/anesthesia_website
    /css
        style.css
    /js
        script.js
    /data
        roster.csv
        OR.csv
        oncall.csv
    /includes
        header.php
        footer.php
    index.php
    script.php
